### ISSUE TITLE
Provide environmental details in README

### ISSUE THREAD

**Issue by SmartHypercube** [Cloud-and-Distributed-Systems/Erms#6]
Some issues we encountered seem to be related to the specific installation and configuration of Kubernetes and Prometheus. The README does not provide detailed information on these aspects. To minimize discrepancies due to environmental differences, could you provide more details, such as the operating system version, versions of Kubernetes and Prometheus, installation methods for Kubernetes and Prometheus, and any modifications made to the default configurations?

**Comment by Nick-LCY** [comment]
Hi, since we have performed AE quite months ago, I cannot provide you the information about the version for AE cluster. But I can give you the version we are currently using.
| Software | Version |
|-----------|----------|
| OS | Ubuntu 20.04.5 |
| Docker | 20.10.22 |
| Kubernetes | 1.23.2 |
| Prometheus | 2.37.0 |


We followed the official installation instructions provided by [Docker](https://docs.docker.com/engine/install/ubuntu/) and [Kubernetes](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/), and used [Prometheus Helm Charts](https://github.com/prometheus-community/helm-charts) to install Prometheus.

In addition, two PromQL needs to be changed under v2.37.0 of Prometheus:
1. `utils/prometheus.py`, line 33 to 36, change to:
    ```python
   prometheus_query = (
       f"sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{{{constraint}}}) by (container, pod)/"
       + f'sum(kube_pod_container_resource_limits{{{constraint}, resource="cpu"}}) by (container, pod) * 100'
   )
   ```
2. `utils/prometheus.py`, line 54 to 57, change to:
   ```python
   query = (
       f"sum(node_namespace_pod_container:container_memory_working_set_bytes{{{constraint}}}) by (pod) / "
       f'sum(kube_pod_container_resource_limits{{{constraint}, resource="memory"}}) by (pod) * 100'
   )
   ```
If this doesn't work, you need to find out which PromQL can give you the CPU and memory usage information, grouped by pod level, and range from 1 to 100.

**Comment by SmartHypercube** [comment]
Thank you very much! I'll close these issues for now and comment if we have more questions.

**Comment by SmartHypercube** [comment]
Hi! Hope you don't mind a few more questions:
1. We are not very familiar with Helm, is there any way to install Prometheus 2.37.0 using Helm Charts? It seems the nearest two available versions are 2.36.2 (chart version 15.14.0) and 2.39.1 (chart version 15.15.0).
2. What is the exact command (and config files, etc.) you used to install and set up Prometheus? Do you choose the chart `prometheus-community/kube-prometheus-stack` or `prometheus-community/prometheus`?
3. Did you use a custom `values.yaml` for Prometheus?

**Comment by Nick-LCY** [comment]
Hi, we used the following command:
```bash
helm install monitor prometheus-community/kube-prometheus-stack --version 39.11.0 -n monitor
```

And when the installation is finished, we edit the service `monitor-kube-prometheus-st-prometheus` and make it as a `NodePort`.

We didn't use any custom `values.yaml`

**Comment by SmartHypercube** [comment]
Thanks! Worked like a charm.
